### PR TITLE
:sparkles: Android V2 Embedding

### PR DESCRIPTION
**Pull request by jrmessias**
Migrate to works with Android V2 Embedding

### CODE REVIEW

**Comment by fuadarradhi** [comment]
cool, thanks.

**Comment by IvoBiaus** [comment]
Damn.. i was using that function...

**Comment by fuadarradhi** [comment]
@IvoBiaus removed function?

**Comment by IvoBiaus** [comment]
yeah, the removed function "openSetting"

**Comment by fuadarradhi** [comment]
@IvoBiaus please try the latest version 2.0.2, 
we've got the function back

**Comment by IvoBiaus** [comment]
great, thanks 👌

**Pull request merged**
